// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_metrics_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_metrics_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_metrics_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_metrics_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[10]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_metrics_2eproto;
namespace io {
namespace prometheus {
namespace client {
class Bucket;
class BucketDefaultTypeInternal;
extern BucketDefaultTypeInternal _Bucket_default_instance_;
class Counter;
class CounterDefaultTypeInternal;
extern CounterDefaultTypeInternal _Counter_default_instance_;
class Gauge;
class GaugeDefaultTypeInternal;
extern GaugeDefaultTypeInternal _Gauge_default_instance_;
class Histogram;
class HistogramDefaultTypeInternal;
extern HistogramDefaultTypeInternal _Histogram_default_instance_;
class LabelPair;
class LabelPairDefaultTypeInternal;
extern LabelPairDefaultTypeInternal _LabelPair_default_instance_;
class Metric;
class MetricDefaultTypeInternal;
extern MetricDefaultTypeInternal _Metric_default_instance_;
class MetricFamily;
class MetricFamilyDefaultTypeInternal;
extern MetricFamilyDefaultTypeInternal _MetricFamily_default_instance_;
class Quantile;
class QuantileDefaultTypeInternal;
extern QuantileDefaultTypeInternal _Quantile_default_instance_;
class Summary;
class SummaryDefaultTypeInternal;
extern SummaryDefaultTypeInternal _Summary_default_instance_;
class Untyped;
class UntypedDefaultTypeInternal;
extern UntypedDefaultTypeInternal _Untyped_default_instance_;
}  // namespace client
}  // namespace prometheus
}  // namespace io
PROTOBUF_NAMESPACE_OPEN
template<> ::io::prometheus::client::Bucket* Arena::CreateMaybeMessage<::io::prometheus::client::Bucket>(Arena*);
template<> ::io::prometheus::client::Counter* Arena::CreateMaybeMessage<::io::prometheus::client::Counter>(Arena*);
template<> ::io::prometheus::client::Gauge* Arena::CreateMaybeMessage<::io::prometheus::client::Gauge>(Arena*);
template<> ::io::prometheus::client::Histogram* Arena::CreateMaybeMessage<::io::prometheus::client::Histogram>(Arena*);
template<> ::io::prometheus::client::LabelPair* Arena::CreateMaybeMessage<::io::prometheus::client::LabelPair>(Arena*);
template<> ::io::prometheus::client::Metric* Arena::CreateMaybeMessage<::io::prometheus::client::Metric>(Arena*);
template<> ::io::prometheus::client::MetricFamily* Arena::CreateMaybeMessage<::io::prometheus::client::MetricFamily>(Arena*);
template<> ::io::prometheus::client::Quantile* Arena::CreateMaybeMessage<::io::prometheus::client::Quantile>(Arena*);
template<> ::io::prometheus::client::Summary* Arena::CreateMaybeMessage<::io::prometheus::client::Summary>(Arena*);
template<> ::io::prometheus::client::Untyped* Arena::CreateMaybeMessage<::io::prometheus::client::Untyped>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace io {
namespace prometheus {
namespace client {

enum MetricType : int {
  COUNTER = 0,
  GAUGE = 1,
  SUMMARY = 2,
  UNTYPED = 3,
  HISTOGRAM = 4
};
bool MetricType_IsValid(int value);
constexpr MetricType MetricType_MIN = COUNTER;
constexpr MetricType MetricType_MAX = HISTOGRAM;
constexpr int MetricType_ARRAYSIZE = MetricType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MetricType_descriptor();
template<typename T>
inline const std::string& MetricType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MetricType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MetricType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MetricType_descriptor(), enum_t_value);
}
inline bool MetricType_Parse(
    const std::string& name, MetricType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MetricType>(
    MetricType_descriptor(), name, value);
}
// ===================================================================

class LabelPair :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.LabelPair) */ {
 public:
  LabelPair();
  virtual ~LabelPair();

  LabelPair(const LabelPair& from);
  LabelPair(LabelPair&& from) noexcept
    : LabelPair() {
    *this = ::std::move(from);
  }

  inline LabelPair& operator=(const LabelPair& from) {
    CopyFrom(from);
    return *this;
  }
  inline LabelPair& operator=(LabelPair&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LabelPair& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LabelPair* internal_default_instance() {
    return reinterpret_cast<const LabelPair*>(
               &_LabelPair_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LabelPair& a, LabelPair& b) {
    a.Swap(&b);
  }
  inline void Swap(LabelPair* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LabelPair* New() const final {
    return CreateMaybeMessage<LabelPair>(nullptr);
  }

  LabelPair* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LabelPair>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LabelPair& from);
  void MergeFrom(const LabelPair& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LabelPair* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "io.prometheus.client.LabelPair";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_metrics_2eproto);
    return ::descriptor_table_metrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);

  // optional string value = 2;
  bool has_value() const;
  void clear_value();
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.LabelPair)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class Gauge :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Gauge) */ {
 public:
  Gauge();
  virtual ~Gauge();

  Gauge(const Gauge& from);
  Gauge(Gauge&& from) noexcept
    : Gauge() {
    *this = ::std::move(from);
  }

  inline Gauge& operator=(const Gauge& from) {
    CopyFrom(from);
    return *this;
  }
  inline Gauge& operator=(Gauge&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Gauge& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Gauge* internal_default_instance() {
    return reinterpret_cast<const Gauge*>(
               &_Gauge_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Gauge& a, Gauge& b) {
    a.Swap(&b);
  }
  inline void Swap(Gauge* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Gauge* New() const final {
    return CreateMaybeMessage<Gauge>(nullptr);
  }

  Gauge* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Gauge>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Gauge& from);
  void MergeFrom(const Gauge& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Gauge* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "io.prometheus.client.Gauge";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_metrics_2eproto);
    return ::descriptor_table_metrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // optional double value = 1;
  bool has_value() const;
  void clear_value();
  double value() const;
  void set_value(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Gauge)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double value_;
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class Counter :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Counter) */ {
 public:
  Counter();
  virtual ~Counter();

  Counter(const Counter& from);
  Counter(Counter&& from) noexcept
    : Counter() {
    *this = ::std::move(from);
  }

  inline Counter& operator=(const Counter& from) {
    CopyFrom(from);
    return *this;
  }
  inline Counter& operator=(Counter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Counter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Counter* internal_default_instance() {
    return reinterpret_cast<const Counter*>(
               &_Counter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Counter& a, Counter& b) {
    a.Swap(&b);
  }
  inline void Swap(Counter* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Counter* New() const final {
    return CreateMaybeMessage<Counter>(nullptr);
  }

  Counter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Counter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Counter& from);
  void MergeFrom(const Counter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Counter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "io.prometheus.client.Counter";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_metrics_2eproto);
    return ::descriptor_table_metrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // optional double value = 1;
  bool has_value() const;
  void clear_value();
  double value() const;
  void set_value(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Counter)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double value_;
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class Quantile :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Quantile) */ {
 public:
  Quantile();
  virtual ~Quantile();

  Quantile(const Quantile& from);
  Quantile(Quantile&& from) noexcept
    : Quantile() {
    *this = ::std::move(from);
  }

  inline Quantile& operator=(const Quantile& from) {
    CopyFrom(from);
    return *this;
  }
  inline Quantile& operator=(Quantile&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Quantile& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Quantile* internal_default_instance() {
    return reinterpret_cast<const Quantile*>(
               &_Quantile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Quantile& a, Quantile& b) {
    a.Swap(&b);
  }
  inline void Swap(Quantile* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Quantile* New() const final {
    return CreateMaybeMessage<Quantile>(nullptr);
  }

  Quantile* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Quantile>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Quantile& from);
  void MergeFrom(const Quantile& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Quantile* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "io.prometheus.client.Quantile";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_metrics_2eproto);
    return ::descriptor_table_metrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuantileFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // optional double quantile = 1;
  bool has_quantile() const;
  void clear_quantile();
  double quantile() const;
  void set_quantile(double value);

  // optional double value = 2;
  bool has_value() const;
  void clear_value();
  double value() const;
  void set_value(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Quantile)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double quantile_;
  double value_;
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class Summary :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Summary) */ {
 public:
  Summary();
  virtual ~Summary();

  Summary(const Summary& from);
  Summary(Summary&& from) noexcept
    : Summary() {
    *this = ::std::move(from);
  }

  inline Summary& operator=(const Summary& from) {
    CopyFrom(from);
    return *this;
  }
  inline Summary& operator=(Summary&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Summary& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Summary* internal_default_instance() {
    return reinterpret_cast<const Summary*>(
               &_Summary_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Summary& a, Summary& b) {
    a.Swap(&b);
  }
  inline void Swap(Summary* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Summary* New() const final {
    return CreateMaybeMessage<Summary>(nullptr);
  }

  Summary* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Summary>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Summary& from);
  void MergeFrom(const Summary& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Summary* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "io.prometheus.client.Summary";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_metrics_2eproto);
    return ::descriptor_table_metrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuantileFieldNumber = 3,
    kSampleCountFieldNumber = 1,
    kSampleSumFieldNumber = 2,
  };
  // repeated .io.prometheus.client.Quantile quantile = 3;
  int quantile_size() const;
  void clear_quantile();
  ::io::prometheus::client::Quantile* mutable_quantile(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Quantile >*
      mutable_quantile();
  const ::io::prometheus::client::Quantile& quantile(int index) const;
  ::io::prometheus::client::Quantile* add_quantile();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Quantile >&
      quantile() const;

  // optional uint64 sample_count = 1;
  bool has_sample_count() const;
  void clear_sample_count();
  ::PROTOBUF_NAMESPACE_ID::uint64 sample_count() const;
  void set_sample_count(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // optional double sample_sum = 2;
  bool has_sample_sum() const;
  void clear_sample_sum();
  double sample_sum() const;
  void set_sample_sum(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Summary)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Quantile > quantile_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sample_count_;
  double sample_sum_;
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class Untyped :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Untyped) */ {
 public:
  Untyped();
  virtual ~Untyped();

  Untyped(const Untyped& from);
  Untyped(Untyped&& from) noexcept
    : Untyped() {
    *this = ::std::move(from);
  }

  inline Untyped& operator=(const Untyped& from) {
    CopyFrom(from);
    return *this;
  }
  inline Untyped& operator=(Untyped&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Untyped& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Untyped* internal_default_instance() {
    return reinterpret_cast<const Untyped*>(
               &_Untyped_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Untyped& a, Untyped& b) {
    a.Swap(&b);
  }
  inline void Swap(Untyped* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Untyped* New() const final {
    return CreateMaybeMessage<Untyped>(nullptr);
  }

  Untyped* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Untyped>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Untyped& from);
  void MergeFrom(const Untyped& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Untyped* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "io.prometheus.client.Untyped";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_metrics_2eproto);
    return ::descriptor_table_metrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // optional double value = 1;
  bool has_value() const;
  void clear_value();
  double value() const;
  void set_value(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Untyped)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double value_;
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class Histogram :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Histogram) */ {
 public:
  Histogram();
  virtual ~Histogram();

  Histogram(const Histogram& from);
  Histogram(Histogram&& from) noexcept
    : Histogram() {
    *this = ::std::move(from);
  }

  inline Histogram& operator=(const Histogram& from) {
    CopyFrom(from);
    return *this;
  }
  inline Histogram& operator=(Histogram&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Histogram& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Histogram* internal_default_instance() {
    return reinterpret_cast<const Histogram*>(
               &_Histogram_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Histogram& a, Histogram& b) {
    a.Swap(&b);
  }
  inline void Swap(Histogram* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Histogram* New() const final {
    return CreateMaybeMessage<Histogram>(nullptr);
  }

  Histogram* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Histogram>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Histogram& from);
  void MergeFrom(const Histogram& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Histogram* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "io.prometheus.client.Histogram";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_metrics_2eproto);
    return ::descriptor_table_metrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBucketFieldNumber = 3,
    kSampleCountFieldNumber = 1,
    kSampleSumFieldNumber = 2,
  };
  // repeated .io.prometheus.client.Bucket bucket = 3;
  int bucket_size() const;
  void clear_bucket();
  ::io::prometheus::client::Bucket* mutable_bucket(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Bucket >*
      mutable_bucket();
  const ::io::prometheus::client::Bucket& bucket(int index) const;
  ::io::prometheus::client::Bucket* add_bucket();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Bucket >&
      bucket() const;

  // optional uint64 sample_count = 1;
  bool has_sample_count() const;
  void clear_sample_count();
  ::PROTOBUF_NAMESPACE_ID::uint64 sample_count() const;
  void set_sample_count(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // optional double sample_sum = 2;
  bool has_sample_sum() const;
  void clear_sample_sum();
  double sample_sum() const;
  void set_sample_sum(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Histogram)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Bucket > bucket_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sample_count_;
  double sample_sum_;
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class Bucket :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Bucket) */ {
 public:
  Bucket();
  virtual ~Bucket();

  Bucket(const Bucket& from);
  Bucket(Bucket&& from) noexcept
    : Bucket() {
    *this = ::std::move(from);
  }

  inline Bucket& operator=(const Bucket& from) {
    CopyFrom(from);
    return *this;
  }
  inline Bucket& operator=(Bucket&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Bucket& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Bucket* internal_default_instance() {
    return reinterpret_cast<const Bucket*>(
               &_Bucket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(Bucket& a, Bucket& b) {
    a.Swap(&b);
  }
  inline void Swap(Bucket* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Bucket* New() const final {
    return CreateMaybeMessage<Bucket>(nullptr);
  }

  Bucket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Bucket>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Bucket& from);
  void MergeFrom(const Bucket& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Bucket* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "io.prometheus.client.Bucket";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_metrics_2eproto);
    return ::descriptor_table_metrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCumulativeCountFieldNumber = 1,
    kUpperBoundFieldNumber = 2,
  };
  // optional uint64 cumulative_count = 1;
  bool has_cumulative_count() const;
  void clear_cumulative_count();
  ::PROTOBUF_NAMESPACE_ID::uint64 cumulative_count() const;
  void set_cumulative_count(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // optional double upper_bound = 2;
  bool has_upper_bound() const;
  void clear_upper_bound();
  double upper_bound() const;
  void set_upper_bound(double value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Bucket)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint64 cumulative_count_;
  double upper_bound_;
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class Metric :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.Metric) */ {
 public:
  Metric();
  virtual ~Metric();

  Metric(const Metric& from);
  Metric(Metric&& from) noexcept
    : Metric() {
    *this = ::std::move(from);
  }

  inline Metric& operator=(const Metric& from) {
    CopyFrom(from);
    return *this;
  }
  inline Metric& operator=(Metric&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Metric& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Metric* internal_default_instance() {
    return reinterpret_cast<const Metric*>(
               &_Metric_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(Metric& a, Metric& b) {
    a.Swap(&b);
  }
  inline void Swap(Metric* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Metric* New() const final {
    return CreateMaybeMessage<Metric>(nullptr);
  }

  Metric* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Metric>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Metric& from);
  void MergeFrom(const Metric& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Metric* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "io.prometheus.client.Metric";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_metrics_2eproto);
    return ::descriptor_table_metrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLabelFieldNumber = 1,
    kGaugeFieldNumber = 2,
    kCounterFieldNumber = 3,
    kSummaryFieldNumber = 4,
    kUntypedFieldNumber = 5,
    kHistogramFieldNumber = 7,
    kTimestampMsFieldNumber = 6,
  };
  // repeated .io.prometheus.client.LabelPair label = 1;
  int label_size() const;
  void clear_label();
  ::io::prometheus::client::LabelPair* mutable_label(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::LabelPair >*
      mutable_label();
  const ::io::prometheus::client::LabelPair& label(int index) const;
  ::io::prometheus::client::LabelPair* add_label();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::LabelPair >&
      label() const;

  // optional .io.prometheus.client.Gauge gauge = 2;
  bool has_gauge() const;
  void clear_gauge();
  const ::io::prometheus::client::Gauge& gauge() const;
  ::io::prometheus::client::Gauge* release_gauge();
  ::io::prometheus::client::Gauge* mutable_gauge();
  void set_allocated_gauge(::io::prometheus::client::Gauge* gauge);

  // optional .io.prometheus.client.Counter counter = 3;
  bool has_counter() const;
  void clear_counter();
  const ::io::prometheus::client::Counter& counter() const;
  ::io::prometheus::client::Counter* release_counter();
  ::io::prometheus::client::Counter* mutable_counter();
  void set_allocated_counter(::io::prometheus::client::Counter* counter);

  // optional .io.prometheus.client.Summary summary = 4;
  bool has_summary() const;
  void clear_summary();
  const ::io::prometheus::client::Summary& summary() const;
  ::io::prometheus::client::Summary* release_summary();
  ::io::prometheus::client::Summary* mutable_summary();
  void set_allocated_summary(::io::prometheus::client::Summary* summary);

  // optional .io.prometheus.client.Untyped untyped = 5;
  bool has_untyped() const;
  void clear_untyped();
  const ::io::prometheus::client::Untyped& untyped() const;
  ::io::prometheus::client::Untyped* release_untyped();
  ::io::prometheus::client::Untyped* mutable_untyped();
  void set_allocated_untyped(::io::prometheus::client::Untyped* untyped);

  // optional .io.prometheus.client.Histogram histogram = 7;
  bool has_histogram() const;
  void clear_histogram();
  const ::io::prometheus::client::Histogram& histogram() const;
  ::io::prometheus::client::Histogram* release_histogram();
  ::io::prometheus::client::Histogram* mutable_histogram();
  void set_allocated_histogram(::io::prometheus::client::Histogram* histogram);

  // optional int64 timestamp_ms = 6;
  bool has_timestamp_ms() const;
  void clear_timestamp_ms();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ms() const;
  void set_timestamp_ms(::PROTOBUF_NAMESPACE_ID::int64 value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.Metric)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::LabelPair > label_;
  ::io::prometheus::client::Gauge* gauge_;
  ::io::prometheus::client::Counter* counter_;
  ::io::prometheus::client::Summary* summary_;
  ::io::prometheus::client::Untyped* untyped_;
  ::io::prometheus::client::Histogram* histogram_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ms_;
  friend struct ::TableStruct_metrics_2eproto;
};
// -------------------------------------------------------------------

class MetricFamily :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:io.prometheus.client.MetricFamily) */ {
 public:
  MetricFamily();
  virtual ~MetricFamily();

  MetricFamily(const MetricFamily& from);
  MetricFamily(MetricFamily&& from) noexcept
    : MetricFamily() {
    *this = ::std::move(from);
  }

  inline MetricFamily& operator=(const MetricFamily& from) {
    CopyFrom(from);
    return *this;
  }
  inline MetricFamily& operator=(MetricFamily&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MetricFamily& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MetricFamily* internal_default_instance() {
    return reinterpret_cast<const MetricFamily*>(
               &_MetricFamily_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(MetricFamily& a, MetricFamily& b) {
    a.Swap(&b);
  }
  inline void Swap(MetricFamily* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MetricFamily* New() const final {
    return CreateMaybeMessage<MetricFamily>(nullptr);
  }

  MetricFamily* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MetricFamily>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MetricFamily& from);
  void MergeFrom(const MetricFamily& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MetricFamily* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "io.prometheus.client.MetricFamily";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_metrics_2eproto);
    return ::descriptor_table_metrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMetricFieldNumber = 4,
    kNameFieldNumber = 1,
    kHelpFieldNumber = 2,
    kTypeFieldNumber = 3,
  };
  // repeated .io.prometheus.client.Metric metric = 4;
  int metric_size() const;
  void clear_metric();
  ::io::prometheus::client::Metric* mutable_metric(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Metric >*
      mutable_metric();
  const ::io::prometheus::client::Metric& metric(int index) const;
  ::io::prometheus::client::Metric* add_metric();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Metric >&
      metric() const;

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);

  // optional string help = 2;
  bool has_help() const;
  void clear_help();
  const std::string& help() const;
  void set_help(const std::string& value);
  void set_help(std::string&& value);
  void set_help(const char* value);
  void set_help(const char* value, size_t size);
  std::string* mutable_help();
  std::string* release_help();
  void set_allocated_help(std::string* help);

  // optional .io.prometheus.client.MetricType type = 3;
  bool has_type() const;
  void clear_type();
  ::io::prometheus::client::MetricType type() const;
  void set_type(::io::prometheus::client::MetricType value);

  // @@protoc_insertion_point(class_scope:io.prometheus.client.MetricFamily)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Metric > metric_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr help_;
  int type_;
  friend struct ::TableStruct_metrics_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LabelPair

// optional string name = 1;
inline bool LabelPair::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LabelPair::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& LabelPair::name() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.LabelPair.name)
  return name_.GetNoArena();
}
inline void LabelPair::set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:io.prometheus.client.LabelPair.name)
}
inline void LabelPair::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:io.prometheus.client.LabelPair.name)
}
inline void LabelPair::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:io.prometheus.client.LabelPair.name)
}
inline void LabelPair::set_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:io.prometheus.client.LabelPair.name)
}
inline std::string* LabelPair::mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.LabelPair.name)
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* LabelPair::release_name() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.LabelPair.name)
  if (!has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void LabelPair::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.LabelPair.name)
}

// optional string value = 2;
inline bool LabelPair::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LabelPair::clear_value() {
  value_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& LabelPair::value() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.LabelPair.value)
  return value_.GetNoArena();
}
inline void LabelPair::set_value(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:io.prometheus.client.LabelPair.value)
}
inline void LabelPair::set_value(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  value_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:io.prometheus.client.LabelPair.value)
}
inline void LabelPair::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:io.prometheus.client.LabelPair.value)
}
inline void LabelPair::set_value(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:io.prometheus.client.LabelPair.value)
}
inline std::string* LabelPair::mutable_value() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.LabelPair.value)
  return value_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* LabelPair::release_value() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.LabelPair.value)
  if (!has_value()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return value_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void LabelPair::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  value_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.LabelPair.value)
}

// -------------------------------------------------------------------

// Gauge

// optional double value = 1;
inline bool Gauge::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Gauge::clear_value() {
  value_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double Gauge::value() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Gauge.value)
  return value_;
}
inline void Gauge::set_value(double value) {
  _has_bits_[0] |= 0x00000001u;
  value_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Gauge.value)
}

// -------------------------------------------------------------------

// Counter

// optional double value = 1;
inline bool Counter::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Counter::clear_value() {
  value_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double Counter::value() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Counter.value)
  return value_;
}
inline void Counter::set_value(double value) {
  _has_bits_[0] |= 0x00000001u;
  value_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Counter.value)
}

// -------------------------------------------------------------------

// Quantile

// optional double quantile = 1;
inline bool Quantile::has_quantile() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Quantile::clear_quantile() {
  quantile_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double Quantile::quantile() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Quantile.quantile)
  return quantile_;
}
inline void Quantile::set_quantile(double value) {
  _has_bits_[0] |= 0x00000001u;
  quantile_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Quantile.quantile)
}

// optional double value = 2;
inline bool Quantile::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Quantile::clear_value() {
  value_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double Quantile::value() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Quantile.value)
  return value_;
}
inline void Quantile::set_value(double value) {
  _has_bits_[0] |= 0x00000002u;
  value_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Quantile.value)
}

// -------------------------------------------------------------------

// Summary

// optional uint64 sample_count = 1;
inline bool Summary::has_sample_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Summary::clear_sample_count() {
  sample_count_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Summary::sample_count() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Summary.sample_count)
  return sample_count_;
}
inline void Summary::set_sample_count(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  sample_count_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Summary.sample_count)
}

// optional double sample_sum = 2;
inline bool Summary::has_sample_sum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Summary::clear_sample_sum() {
  sample_sum_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double Summary::sample_sum() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Summary.sample_sum)
  return sample_sum_;
}
inline void Summary::set_sample_sum(double value) {
  _has_bits_[0] |= 0x00000002u;
  sample_sum_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Summary.sample_sum)
}

// repeated .io.prometheus.client.Quantile quantile = 3;
inline int Summary::quantile_size() const {
  return quantile_.size();
}
inline void Summary::clear_quantile() {
  quantile_.Clear();
}
inline ::io::prometheus::client::Quantile* Summary::mutable_quantile(int index) {
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Summary.quantile)
  return quantile_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Quantile >*
Summary::mutable_quantile() {
  // @@protoc_insertion_point(field_mutable_list:io.prometheus.client.Summary.quantile)
  return &quantile_;
}
inline const ::io::prometheus::client::Quantile& Summary::quantile(int index) const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Summary.quantile)
  return quantile_.Get(index);
}
inline ::io::prometheus::client::Quantile* Summary::add_quantile() {
  // @@protoc_insertion_point(field_add:io.prometheus.client.Summary.quantile)
  return quantile_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Quantile >&
Summary::quantile() const {
  // @@protoc_insertion_point(field_list:io.prometheus.client.Summary.quantile)
  return quantile_;
}

// -------------------------------------------------------------------

// Untyped

// optional double value = 1;
inline bool Untyped::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Untyped::clear_value() {
  value_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double Untyped::value() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Untyped.value)
  return value_;
}
inline void Untyped::set_value(double value) {
  _has_bits_[0] |= 0x00000001u;
  value_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Untyped.value)
}

// -------------------------------------------------------------------

// Histogram

// optional uint64 sample_count = 1;
inline bool Histogram::has_sample_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Histogram::clear_sample_count() {
  sample_count_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Histogram::sample_count() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Histogram.sample_count)
  return sample_count_;
}
inline void Histogram::set_sample_count(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  sample_count_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Histogram.sample_count)
}

// optional double sample_sum = 2;
inline bool Histogram::has_sample_sum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Histogram::clear_sample_sum() {
  sample_sum_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double Histogram::sample_sum() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Histogram.sample_sum)
  return sample_sum_;
}
inline void Histogram::set_sample_sum(double value) {
  _has_bits_[0] |= 0x00000002u;
  sample_sum_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Histogram.sample_sum)
}

// repeated .io.prometheus.client.Bucket bucket = 3;
inline int Histogram::bucket_size() const {
  return bucket_.size();
}
inline void Histogram::clear_bucket() {
  bucket_.Clear();
}
inline ::io::prometheus::client::Bucket* Histogram::mutable_bucket(int index) {
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Histogram.bucket)
  return bucket_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Bucket >*
Histogram::mutable_bucket() {
  // @@protoc_insertion_point(field_mutable_list:io.prometheus.client.Histogram.bucket)
  return &bucket_;
}
inline const ::io::prometheus::client::Bucket& Histogram::bucket(int index) const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Histogram.bucket)
  return bucket_.Get(index);
}
inline ::io::prometheus::client::Bucket* Histogram::add_bucket() {
  // @@protoc_insertion_point(field_add:io.prometheus.client.Histogram.bucket)
  return bucket_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Bucket >&
Histogram::bucket() const {
  // @@protoc_insertion_point(field_list:io.prometheus.client.Histogram.bucket)
  return bucket_;
}

// -------------------------------------------------------------------

// Bucket

// optional uint64 cumulative_count = 1;
inline bool Bucket::has_cumulative_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Bucket::clear_cumulative_count() {
  cumulative_count_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Bucket::cumulative_count() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Bucket.cumulative_count)
  return cumulative_count_;
}
inline void Bucket::set_cumulative_count(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  cumulative_count_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Bucket.cumulative_count)
}

// optional double upper_bound = 2;
inline bool Bucket::has_upper_bound() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Bucket::clear_upper_bound() {
  upper_bound_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double Bucket::upper_bound() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Bucket.upper_bound)
  return upper_bound_;
}
inline void Bucket::set_upper_bound(double value) {
  _has_bits_[0] |= 0x00000002u;
  upper_bound_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Bucket.upper_bound)
}

// -------------------------------------------------------------------

// Metric

// repeated .io.prometheus.client.LabelPair label = 1;
inline int Metric::label_size() const {
  return label_.size();
}
inline void Metric::clear_label() {
  label_.Clear();
}
inline ::io::prometheus::client::LabelPair* Metric::mutable_label(int index) {
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.label)
  return label_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::LabelPair >*
Metric::mutable_label() {
  // @@protoc_insertion_point(field_mutable_list:io.prometheus.client.Metric.label)
  return &label_;
}
inline const ::io::prometheus::client::LabelPair& Metric::label(int index) const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.label)
  return label_.Get(index);
}
inline ::io::prometheus::client::LabelPair* Metric::add_label() {
  // @@protoc_insertion_point(field_add:io.prometheus.client.Metric.label)
  return label_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::LabelPair >&
Metric::label() const {
  // @@protoc_insertion_point(field_list:io.prometheus.client.Metric.label)
  return label_;
}

// optional .io.prometheus.client.Gauge gauge = 2;
inline bool Metric::has_gauge() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Metric::clear_gauge() {
  if (gauge_ != nullptr) gauge_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::io::prometheus::client::Gauge& Metric::gauge() const {
  const ::io::prometheus::client::Gauge* p = gauge_;
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.gauge)
  return p != nullptr ? *p : *reinterpret_cast<const ::io::prometheus::client::Gauge*>(
      &::io::prometheus::client::_Gauge_default_instance_);
}
inline ::io::prometheus::client::Gauge* Metric::release_gauge() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.Metric.gauge)
  _has_bits_[0] &= ~0x00000001u;
  ::io::prometheus::client::Gauge* temp = gauge_;
  gauge_ = nullptr;
  return temp;
}
inline ::io::prometheus::client::Gauge* Metric::mutable_gauge() {
  _has_bits_[0] |= 0x00000001u;
  if (gauge_ == nullptr) {
    auto* p = CreateMaybeMessage<::io::prometheus::client::Gauge>(GetArenaNoVirtual());
    gauge_ = p;
  }
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.gauge)
  return gauge_;
}
inline void Metric::set_allocated_gauge(::io::prometheus::client::Gauge* gauge) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete gauge_;
  }
  if (gauge) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      gauge = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, gauge, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  gauge_ = gauge;
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.Metric.gauge)
}

// optional .io.prometheus.client.Counter counter = 3;
inline bool Metric::has_counter() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Metric::clear_counter() {
  if (counter_ != nullptr) counter_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::io::prometheus::client::Counter& Metric::counter() const {
  const ::io::prometheus::client::Counter* p = counter_;
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.counter)
  return p != nullptr ? *p : *reinterpret_cast<const ::io::prometheus::client::Counter*>(
      &::io::prometheus::client::_Counter_default_instance_);
}
inline ::io::prometheus::client::Counter* Metric::release_counter() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.Metric.counter)
  _has_bits_[0] &= ~0x00000002u;
  ::io::prometheus::client::Counter* temp = counter_;
  counter_ = nullptr;
  return temp;
}
inline ::io::prometheus::client::Counter* Metric::mutable_counter() {
  _has_bits_[0] |= 0x00000002u;
  if (counter_ == nullptr) {
    auto* p = CreateMaybeMessage<::io::prometheus::client::Counter>(GetArenaNoVirtual());
    counter_ = p;
  }
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.counter)
  return counter_;
}
inline void Metric::set_allocated_counter(::io::prometheus::client::Counter* counter) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete counter_;
  }
  if (counter) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      counter = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, counter, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  counter_ = counter;
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.Metric.counter)
}

// optional .io.prometheus.client.Summary summary = 4;
inline bool Metric::has_summary() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Metric::clear_summary() {
  if (summary_ != nullptr) summary_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::io::prometheus::client::Summary& Metric::summary() const {
  const ::io::prometheus::client::Summary* p = summary_;
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.summary)
  return p != nullptr ? *p : *reinterpret_cast<const ::io::prometheus::client::Summary*>(
      &::io::prometheus::client::_Summary_default_instance_);
}
inline ::io::prometheus::client::Summary* Metric::release_summary() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.Metric.summary)
  _has_bits_[0] &= ~0x00000004u;
  ::io::prometheus::client::Summary* temp = summary_;
  summary_ = nullptr;
  return temp;
}
inline ::io::prometheus::client::Summary* Metric::mutable_summary() {
  _has_bits_[0] |= 0x00000004u;
  if (summary_ == nullptr) {
    auto* p = CreateMaybeMessage<::io::prometheus::client::Summary>(GetArenaNoVirtual());
    summary_ = p;
  }
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.summary)
  return summary_;
}
inline void Metric::set_allocated_summary(::io::prometheus::client::Summary* summary) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete summary_;
  }
  if (summary) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      summary = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, summary, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  summary_ = summary;
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.Metric.summary)
}

// optional .io.prometheus.client.Untyped untyped = 5;
inline bool Metric::has_untyped() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Metric::clear_untyped() {
  if (untyped_ != nullptr) untyped_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::io::prometheus::client::Untyped& Metric::untyped() const {
  const ::io::prometheus::client::Untyped* p = untyped_;
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.untyped)
  return p != nullptr ? *p : *reinterpret_cast<const ::io::prometheus::client::Untyped*>(
      &::io::prometheus::client::_Untyped_default_instance_);
}
inline ::io::prometheus::client::Untyped* Metric::release_untyped() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.Metric.untyped)
  _has_bits_[0] &= ~0x00000008u;
  ::io::prometheus::client::Untyped* temp = untyped_;
  untyped_ = nullptr;
  return temp;
}
inline ::io::prometheus::client::Untyped* Metric::mutable_untyped() {
  _has_bits_[0] |= 0x00000008u;
  if (untyped_ == nullptr) {
    auto* p = CreateMaybeMessage<::io::prometheus::client::Untyped>(GetArenaNoVirtual());
    untyped_ = p;
  }
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.untyped)
  return untyped_;
}
inline void Metric::set_allocated_untyped(::io::prometheus::client::Untyped* untyped) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete untyped_;
  }
  if (untyped) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      untyped = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, untyped, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  untyped_ = untyped;
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.Metric.untyped)
}

// optional .io.prometheus.client.Histogram histogram = 7;
inline bool Metric::has_histogram() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Metric::clear_histogram() {
  if (histogram_ != nullptr) histogram_->Clear();
  _has_bits_[0] &= ~0x00000010u;
}
inline const ::io::prometheus::client::Histogram& Metric::histogram() const {
  const ::io::prometheus::client::Histogram* p = histogram_;
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.histogram)
  return p != nullptr ? *p : *reinterpret_cast<const ::io::prometheus::client::Histogram*>(
      &::io::prometheus::client::_Histogram_default_instance_);
}
inline ::io::prometheus::client::Histogram* Metric::release_histogram() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.Metric.histogram)
  _has_bits_[0] &= ~0x00000010u;
  ::io::prometheus::client::Histogram* temp = histogram_;
  histogram_ = nullptr;
  return temp;
}
inline ::io::prometheus::client::Histogram* Metric::mutable_histogram() {
  _has_bits_[0] |= 0x00000010u;
  if (histogram_ == nullptr) {
    auto* p = CreateMaybeMessage<::io::prometheus::client::Histogram>(GetArenaNoVirtual());
    histogram_ = p;
  }
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.Metric.histogram)
  return histogram_;
}
inline void Metric::set_allocated_histogram(::io::prometheus::client::Histogram* histogram) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete histogram_;
  }
  if (histogram) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      histogram = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, histogram, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  histogram_ = histogram;
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.Metric.histogram)
}

// optional int64 timestamp_ms = 6;
inline bool Metric::has_timestamp_ms() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Metric::clear_timestamp_ms() {
  timestamp_ms_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Metric::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.Metric.timestamp_ms)
  return timestamp_ms_;
}
inline void Metric::set_timestamp_ms(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000020u;
  timestamp_ms_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.Metric.timestamp_ms)
}

// -------------------------------------------------------------------

// MetricFamily

// optional string name = 1;
inline bool MetricFamily::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MetricFamily::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MetricFamily::name() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.MetricFamily.name)
  return name_.GetNoArena();
}
inline void MetricFamily::set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:io.prometheus.client.MetricFamily.name)
}
inline void MetricFamily::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:io.prometheus.client.MetricFamily.name)
}
inline void MetricFamily::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:io.prometheus.client.MetricFamily.name)
}
inline void MetricFamily::set_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:io.prometheus.client.MetricFamily.name)
}
inline std::string* MetricFamily::mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.MetricFamily.name)
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MetricFamily::release_name() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.MetricFamily.name)
  if (!has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MetricFamily::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.MetricFamily.name)
}

// optional string help = 2;
inline bool MetricFamily::has_help() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MetricFamily::clear_help() {
  help_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& MetricFamily::help() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.MetricFamily.help)
  return help_.GetNoArena();
}
inline void MetricFamily::set_help(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  help_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:io.prometheus.client.MetricFamily.help)
}
inline void MetricFamily::set_help(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  help_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:io.prometheus.client.MetricFamily.help)
}
inline void MetricFamily::set_help(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  help_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:io.prometheus.client.MetricFamily.help)
}
inline void MetricFamily::set_help(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  help_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:io.prometheus.client.MetricFamily.help)
}
inline std::string* MetricFamily::mutable_help() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.MetricFamily.help)
  return help_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MetricFamily::release_help() {
  // @@protoc_insertion_point(field_release:io.prometheus.client.MetricFamily.help)
  if (!has_help()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return help_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MetricFamily::set_allocated_help(std::string* help) {
  if (help != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  help_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), help);
  // @@protoc_insertion_point(field_set_allocated:io.prometheus.client.MetricFamily.help)
}

// optional .io.prometheus.client.MetricType type = 3;
inline bool MetricFamily::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MetricFamily::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::io::prometheus::client::MetricType MetricFamily::type() const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.MetricFamily.type)
  return static_cast< ::io::prometheus::client::MetricType >(type_);
}
inline void MetricFamily::set_type(::io::prometheus::client::MetricType value) {
  assert(::io::prometheus::client::MetricType_IsValid(value));
  _has_bits_[0] |= 0x00000004u;
  type_ = value;
  // @@protoc_insertion_point(field_set:io.prometheus.client.MetricFamily.type)
}

// repeated .io.prometheus.client.Metric metric = 4;
inline int MetricFamily::metric_size() const {
  return metric_.size();
}
inline void MetricFamily::clear_metric() {
  metric_.Clear();
}
inline ::io::prometheus::client::Metric* MetricFamily::mutable_metric(int index) {
  // @@protoc_insertion_point(field_mutable:io.prometheus.client.MetricFamily.metric)
  return metric_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Metric >*
MetricFamily::mutable_metric() {
  // @@protoc_insertion_point(field_mutable_list:io.prometheus.client.MetricFamily.metric)
  return &metric_;
}
inline const ::io::prometheus::client::Metric& MetricFamily::metric(int index) const {
  // @@protoc_insertion_point(field_get:io.prometheus.client.MetricFamily.metric)
  return metric_.Get(index);
}
inline ::io::prometheus::client::Metric* MetricFamily::add_metric() {
  // @@protoc_insertion_point(field_add:io.prometheus.client.MetricFamily.metric)
  return metric_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::io::prometheus::client::Metric >&
MetricFamily::metric() const {
  // @@protoc_insertion_point(field_list:io.prometheus.client.MetricFamily.metric)
  return metric_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace client
}  // namespace prometheus
}  // namespace io

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::io::prometheus::client::MetricType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::io::prometheus::client::MetricType>() {
  return ::io::prometheus::client::MetricType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_metrics_2eproto
